pipelines:
  hop:
    group: hop
    materials:
      repo:
        git: https://github.com/dudadornelles/hop.git
    stages:
      - build:
          tasks:
            - script: echo running this build
