pipelines:
  hop:
    group: hop
    materials:
      repo:
        git: https://github.com/dudadornelles/hop.git
    stages:
      - build:
          tasks:
            - script: >
                virtualenv ~/.hopvenv -p python3 && virtualenv .venv/bin/activate
                make init
                make develop
                make test

